CREATE TABLE  `metzgecl`.`Wrestler` (
	`WrestlerID` INT( 10 ) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`FirstName` VARCHAR( 30 ) NOT NULL ,
	`LastName` VARCHAR( 30 ) NOT NULL ,
	`Class` INT( 4 ) NOT NULL
) ENGINE = MYISAM ;